# Generated by Django 4.1.2 on 2022-10-27 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grooming', models.DateField(blank=True, null=True)),
                ('play_date', models.DateField(blank=True, null=True)),
                ('cuddles', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_schedule', models.TimeField(blank=True, null=True)),
                ('walk_schedule', models.TimeField(blank=True, null=True)),
                ('potty_trips', models.TimeField(blank=True, null=True)),
                ('medicine_schedule', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(null=True)),
                ('visit_type', models.CharField(blank=True, max_length=250, null=True)),
                ('pet_weight', models.CharField(blank=True, max_length=25, null=True)),
                ('shots', models.CharField(blank=True, max_length=500, null=True)),
                ('medicine', models.CharField(blank=True, max_length=500, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('tx_plan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('nickname', models.CharField(max_length=100)),
                ('catchphrase', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointments')),
                ('daily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.daily')),
                ('health', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.health')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pet')),
            ],
        ),
        migrations.AddField(
            model_name='health',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
        ),
        migrations.AddField(
            model_name='daily',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
        ),
    ]
