# Generated by Django 4.1.2 on 2022-10-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='appointments',
            name='cuddles',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='grooming',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='play_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='food_schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='medicine_schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
        ),
        migrations.AddField(
            model_name='daily',
            name='potty_trips',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='walk_schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='medicine',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
        ),
        migrations.AddField(
            model_name='health',
            name='pet_weight',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='shots',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='tx_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet_diary',
            name='daily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.daily'),
        ),
        migrations.AddField(
            model_name='pet_diary',
            name='health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.health'),
        ),
        migrations.AlterField(
            model_name='health',
            name='visit_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pet_diary',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
        ),
    ]
