# Generated by Django 4.1.2 on 2022-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointments_pet_delete_pet_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
