# Generated by Django 4.1.2 on 2022-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_appointments_notes_daily_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
